# Generated by Django 5.2.4 on 2025-09-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='updated_at',
        ),
    ]
